/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProspeccaoRouteImport } from './routes/prospeccao'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as MensagensRouteImport } from './routes/mensagens'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as IaRouteImport } from './routes/ia'
import { Route as GrowthRouteImport } from './routes/growth'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ConteudoRouteImport } from './routes/conteudo'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as BaseConhecimentoRouteImport } from './routes/base-conhecimento'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin.index'
import { Route as ProspeccaoIndexRouteImport } from './routes/prospeccao.index'
import { Route as SuperAdminWorkspacesRouteImport } from './routes/super-admin.workspaces'
import { Route as SuperAdminUsuariosRouteImport } from './routes/super-admin.usuarios'
import { Route as SuperAdminLogsRouteImport } from './routes/super-admin.logs'
import { Route as SuperAdminConfiguracoesRouteImport } from './routes/super-admin.configuracoes'
import { Route as ProspeccaoListaRouteImport } from './routes/prospeccao.lista'
import { Route as ProspeccaoIdRouteImport } from './routes/prospeccao.$id'
import { Route as GrowthDashboardRouteImport } from './routes/growth.dashboard'
import { Route as GrowthCadenciasRouteImport } from './routes/growth.cadencias'
import { Route as EmpresasIdRouteImport } from './routes/empresas.$id'
import { Route as CrmIdRouteImport } from './routes/crm.$id'
import { Route as ProspeccaoIdIndexRouteImport } from './routes/prospeccao.$id.index'
import { Route as EmpresasIdIndexRouteImport } from './routes/empresas.$id.index'
import { Route as CrmIdIndexRouteImport } from './routes/crm.$id.index'
import { Route as ProspeccaoIdProximasAcoesRouteImport } from './routes/prospeccao.$id.proximas-acoes'
import { Route as ProspeccaoIdInteracoesRouteImport } from './routes/prospeccao.$id.interacoes'
import { Route as ProspeccaoIdHistoricoRouteImport } from './routes/prospeccao.$id.historico'
import { Route as ProspeccaoIdEditarRouteImport } from './routes/prospeccao.$id.editar'
import { Route as EmpresasIdTimelineRouteImport } from './routes/empresas.$id.timeline'
import { Route as EmpresasIdSuporteRouteImport } from './routes/empresas.$id.suporte'
import { Route as EmpresasIdProjetosRouteImport } from './routes/empresas.$id.projetos'
import { Route as EmpresasIdFinanceiroRouteImport } from './routes/empresas.$id.financeiro'
import { Route as EmpresasIdContatosRouteImport } from './routes/empresas.$id.contatos'
import { Route as EmpresasIdComercialRouteImport } from './routes/empresas.$id.comercial'
import { Route as CrmIdTimelineRouteImport } from './routes/crm.$id.timeline'
import { Route as CrmIdPropostasRouteImport } from './routes/crm.$id.propostas'
import { Route as CrmIdContratosRouteImport } from './routes/crm.$id.contratos'
import { Route as ApiWebhooksZapzapRouteImport } from './routes/api/webhooks/zapzap'

const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspeccaoRoute = ProspeccaoRouteImport.update({
  id: '/prospeccao',
  path: '/prospeccao',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensRoute = MensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthRoute = GrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudoRoute = ConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseConhecimentoRoute = BaseConhecimentoRouteImport.update({
  id: '/base-conhecimento',
  path: '/base-conhecimento',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const ProspeccaoIndexRoute = ProspeccaoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProspeccaoRoute,
} as any)
const SuperAdminWorkspacesRoute = SuperAdminWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminUsuariosRoute = SuperAdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminLogsRoute = SuperAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminConfiguracoesRoute = SuperAdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => SuperAdminRoute,
} as any)
const ProspeccaoListaRoute = ProspeccaoListaRouteImport.update({
  id: '/lista',
  path: '/lista',
  getParentRoute: () => ProspeccaoRoute,
} as any)
const ProspeccaoIdRoute = ProspeccaoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProspeccaoRoute,
} as any)
const GrowthDashboardRoute = GrowthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => GrowthRoute,
} as any)
const GrowthCadenciasRoute = GrowthCadenciasRouteImport.update({
  id: '/cadencias',
  path: '/cadencias',
  getParentRoute: () => GrowthRoute,
} as any)
const EmpresasIdRoute = EmpresasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EmpresasRoute,
} as any)
const CrmIdRoute = CrmIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CrmRoute,
} as any)
const ProspeccaoIdIndexRoute = ProspeccaoIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProspeccaoIdRoute,
} as any)
const EmpresasIdIndexRoute = EmpresasIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmpresasIdRoute,
} as any)
const CrmIdIndexRoute = CrmIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmIdRoute,
} as any)
const ProspeccaoIdProximasAcoesRoute =
  ProspeccaoIdProximasAcoesRouteImport.update({
    id: '/proximas-acoes',
    path: '/proximas-acoes',
    getParentRoute: () => ProspeccaoIdRoute,
  } as any)
const ProspeccaoIdInteracoesRoute = ProspeccaoIdInteracoesRouteImport.update({
  id: '/interacoes',
  path: '/interacoes',
  getParentRoute: () => ProspeccaoIdRoute,
} as any)
const ProspeccaoIdHistoricoRoute = ProspeccaoIdHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => ProspeccaoIdRoute,
} as any)
const ProspeccaoIdEditarRoute = ProspeccaoIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => ProspeccaoIdRoute,
} as any)
const EmpresasIdTimelineRoute = EmpresasIdTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => EmpresasIdRoute,
} as any)
const EmpresasIdSuporteRoute = EmpresasIdSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => EmpresasIdRoute,
} as any)
const EmpresasIdProjetosRoute = EmpresasIdProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => EmpresasIdRoute,
} as any)
const EmpresasIdFinanceiroRoute = EmpresasIdFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => EmpresasIdRoute,
} as any)
const EmpresasIdContatosRoute = EmpresasIdContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => EmpresasIdRoute,
} as any)
const EmpresasIdComercialRoute = EmpresasIdComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => EmpresasIdRoute,
} as any)
const CrmIdTimelineRoute = CrmIdTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => CrmIdRoute,
} as any)
const CrmIdPropostasRoute = CrmIdPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => CrmIdRoute,
} as any)
const CrmIdContratosRoute = CrmIdContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => CrmIdRoute,
} as any)
const ApiWebhooksZapzapRoute = ApiWebhooksZapzapRouteImport.update({
  id: '/api/webhooks/zapzap',
  path: '/api/webhooks/zapzap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/base-conhecimento': typeof BaseConhecimentoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conteudo': typeof ConteudoRoute
  '/crm': typeof CrmRouteWithChildren
  '/empresas': typeof EmpresasRouteWithChildren
  '/financeiro': typeof FinanceiroRoute
  '/growth': typeof GrowthRouteWithChildren
  '/ia': typeof IaRoute
  '/inbox': typeof InboxRoute
  '/marketing': typeof MarketingRoute
  '/mensagens': typeof MensagensRoute
  '/projetos': typeof ProjetosRoute
  '/prospeccao': typeof ProspeccaoRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/suporte': typeof SuporteRoute
  '/tarefas': typeof TarefasRoute
  '/crm/$id': typeof CrmIdRouteWithChildren
  '/empresas/$id': typeof EmpresasIdRouteWithChildren
  '/growth/cadencias': typeof GrowthCadenciasRoute
  '/growth/dashboard': typeof GrowthDashboardRoute
  '/prospeccao/$id': typeof ProspeccaoIdRouteWithChildren
  '/prospeccao/lista': typeof ProspeccaoListaRoute
  '/super-admin/configuracoes': typeof SuperAdminConfiguracoesRoute
  '/super-admin/logs': typeof SuperAdminLogsRoute
  '/super-admin/usuarios': typeof SuperAdminUsuariosRoute
  '/super-admin/workspaces': typeof SuperAdminWorkspacesRoute
  '/prospeccao/': typeof ProspeccaoIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/api/webhooks/zapzap': typeof ApiWebhooksZapzapRoute
  '/crm/$id/contratos': typeof CrmIdContratosRoute
  '/crm/$id/propostas': typeof CrmIdPropostasRoute
  '/crm/$id/timeline': typeof CrmIdTimelineRoute
  '/empresas/$id/comercial': typeof EmpresasIdComercialRoute
  '/empresas/$id/contatos': typeof EmpresasIdContatosRoute
  '/empresas/$id/financeiro': typeof EmpresasIdFinanceiroRoute
  '/empresas/$id/projetos': typeof EmpresasIdProjetosRoute
  '/empresas/$id/suporte': typeof EmpresasIdSuporteRoute
  '/empresas/$id/timeline': typeof EmpresasIdTimelineRoute
  '/prospeccao/$id/editar': typeof ProspeccaoIdEditarRoute
  '/prospeccao/$id/historico': typeof ProspeccaoIdHistoricoRoute
  '/prospeccao/$id/interacoes': typeof ProspeccaoIdInteracoesRoute
  '/prospeccao/$id/proximas-acoes': typeof ProspeccaoIdProximasAcoesRoute
  '/crm/$id/': typeof CrmIdIndexRoute
  '/empresas/$id/': typeof EmpresasIdIndexRoute
  '/prospeccao/$id/': typeof ProspeccaoIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/base-conhecimento': typeof BaseConhecimentoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conteudo': typeof ConteudoRoute
  '/crm': typeof CrmRouteWithChildren
  '/empresas': typeof EmpresasRouteWithChildren
  '/financeiro': typeof FinanceiroRoute
  '/growth': typeof GrowthRouteWithChildren
  '/ia': typeof IaRoute
  '/inbox': typeof InboxRoute
  '/marketing': typeof MarketingRoute
  '/mensagens': typeof MensagensRoute
  '/projetos': typeof ProjetosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suporte': typeof SuporteRoute
  '/tarefas': typeof TarefasRoute
  '/growth/cadencias': typeof GrowthCadenciasRoute
  '/growth/dashboard': typeof GrowthDashboardRoute
  '/prospeccao/lista': typeof ProspeccaoListaRoute
  '/super-admin/configuracoes': typeof SuperAdminConfiguracoesRoute
  '/super-admin/logs': typeof SuperAdminLogsRoute
  '/super-admin/usuarios': typeof SuperAdminUsuariosRoute
  '/super-admin/workspaces': typeof SuperAdminWorkspacesRoute
  '/prospeccao': typeof ProspeccaoIndexRoute
  '/super-admin': typeof SuperAdminIndexRoute
  '/api/webhooks/zapzap': typeof ApiWebhooksZapzapRoute
  '/crm/$id/contratos': typeof CrmIdContratosRoute
  '/crm/$id/propostas': typeof CrmIdPropostasRoute
  '/crm/$id/timeline': typeof CrmIdTimelineRoute
  '/empresas/$id/comercial': typeof EmpresasIdComercialRoute
  '/empresas/$id/contatos': typeof EmpresasIdContatosRoute
  '/empresas/$id/financeiro': typeof EmpresasIdFinanceiroRoute
  '/empresas/$id/projetos': typeof EmpresasIdProjetosRoute
  '/empresas/$id/suporte': typeof EmpresasIdSuporteRoute
  '/empresas/$id/timeline': typeof EmpresasIdTimelineRoute
  '/prospeccao/$id/editar': typeof ProspeccaoIdEditarRoute
  '/prospeccao/$id/historico': typeof ProspeccaoIdHistoricoRoute
  '/prospeccao/$id/interacoes': typeof ProspeccaoIdInteracoesRoute
  '/prospeccao/$id/proximas-acoes': typeof ProspeccaoIdProximasAcoesRoute
  '/crm/$id': typeof CrmIdIndexRoute
  '/empresas/$id': typeof EmpresasIdIndexRoute
  '/prospeccao/$id': typeof ProspeccaoIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/base-conhecimento': typeof BaseConhecimentoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conteudo': typeof ConteudoRoute
  '/crm': typeof CrmRouteWithChildren
  '/empresas': typeof EmpresasRouteWithChildren
  '/financeiro': typeof FinanceiroRoute
  '/growth': typeof GrowthRouteWithChildren
  '/ia': typeof IaRoute
  '/inbox': typeof InboxRoute
  '/marketing': typeof MarketingRoute
  '/mensagens': typeof MensagensRoute
  '/projetos': typeof ProjetosRoute
  '/prospeccao': typeof ProspeccaoRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/suporte': typeof SuporteRoute
  '/tarefas': typeof TarefasRoute
  '/crm/$id': typeof CrmIdRouteWithChildren
  '/empresas/$id': typeof EmpresasIdRouteWithChildren
  '/growth/cadencias': typeof GrowthCadenciasRoute
  '/growth/dashboard': typeof GrowthDashboardRoute
  '/prospeccao/$id': typeof ProspeccaoIdRouteWithChildren
  '/prospeccao/lista': typeof ProspeccaoListaRoute
  '/super-admin/configuracoes': typeof SuperAdminConfiguracoesRoute
  '/super-admin/logs': typeof SuperAdminLogsRoute
  '/super-admin/usuarios': typeof SuperAdminUsuariosRoute
  '/super-admin/workspaces': typeof SuperAdminWorkspacesRoute
  '/prospeccao/': typeof ProspeccaoIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/api/webhooks/zapzap': typeof ApiWebhooksZapzapRoute
  '/crm/$id/contratos': typeof CrmIdContratosRoute
  '/crm/$id/propostas': typeof CrmIdPropostasRoute
  '/crm/$id/timeline': typeof CrmIdTimelineRoute
  '/empresas/$id/comercial': typeof EmpresasIdComercialRoute
  '/empresas/$id/contatos': typeof EmpresasIdContatosRoute
  '/empresas/$id/financeiro': typeof EmpresasIdFinanceiroRoute
  '/empresas/$id/projetos': typeof EmpresasIdProjetosRoute
  '/empresas/$id/suporte': typeof EmpresasIdSuporteRoute
  '/empresas/$id/timeline': typeof EmpresasIdTimelineRoute
  '/prospeccao/$id/editar': typeof ProspeccaoIdEditarRoute
  '/prospeccao/$id/historico': typeof ProspeccaoIdHistoricoRoute
  '/prospeccao/$id/interacoes': typeof ProspeccaoIdInteracoesRoute
  '/prospeccao/$id/proximas-acoes': typeof ProspeccaoIdProximasAcoesRoute
  '/crm/$id/': typeof CrmIdIndexRoute
  '/empresas/$id/': typeof EmpresasIdIndexRoute
  '/prospeccao/$id/': typeof ProspeccaoIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/base-conhecimento'
    | '/configuracoes'
    | '/conteudo'
    | '/crm'
    | '/empresas'
    | '/financeiro'
    | '/growth'
    | '/ia'
    | '/inbox'
    | '/marketing'
    | '/mensagens'
    | '/projetos'
    | '/prospeccao'
    | '/reset-password'
    | '/super-admin'
    | '/suporte'
    | '/tarefas'
    | '/crm/$id'
    | '/empresas/$id'
    | '/growth/cadencias'
    | '/growth/dashboard'
    | '/prospeccao/$id'
    | '/prospeccao/lista'
    | '/super-admin/configuracoes'
    | '/super-admin/logs'
    | '/super-admin/usuarios'
    | '/super-admin/workspaces'
    | '/prospeccao/'
    | '/super-admin/'
    | '/api/webhooks/zapzap'
    | '/crm/$id/contratos'
    | '/crm/$id/propostas'
    | '/crm/$id/timeline'
    | '/empresas/$id/comercial'
    | '/empresas/$id/contatos'
    | '/empresas/$id/financeiro'
    | '/empresas/$id/projetos'
    | '/empresas/$id/suporte'
    | '/empresas/$id/timeline'
    | '/prospeccao/$id/editar'
    | '/prospeccao/$id/historico'
    | '/prospeccao/$id/interacoes'
    | '/prospeccao/$id/proximas-acoes'
    | '/crm/$id/'
    | '/empresas/$id/'
    | '/prospeccao/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/base-conhecimento'
    | '/configuracoes'
    | '/conteudo'
    | '/crm'
    | '/empresas'
    | '/financeiro'
    | '/growth'
    | '/ia'
    | '/inbox'
    | '/marketing'
    | '/mensagens'
    | '/projetos'
    | '/reset-password'
    | '/suporte'
    | '/tarefas'
    | '/growth/cadencias'
    | '/growth/dashboard'
    | '/prospeccao/lista'
    | '/super-admin/configuracoes'
    | '/super-admin/logs'
    | '/super-admin/usuarios'
    | '/super-admin/workspaces'
    | '/prospeccao'
    | '/super-admin'
    | '/api/webhooks/zapzap'
    | '/crm/$id/contratos'
    | '/crm/$id/propostas'
    | '/crm/$id/timeline'
    | '/empresas/$id/comercial'
    | '/empresas/$id/contatos'
    | '/empresas/$id/financeiro'
    | '/empresas/$id/projetos'
    | '/empresas/$id/suporte'
    | '/empresas/$id/timeline'
    | '/prospeccao/$id/editar'
    | '/prospeccao/$id/historico'
    | '/prospeccao/$id/interacoes'
    | '/prospeccao/$id/proximas-acoes'
    | '/crm/$id'
    | '/empresas/$id'
    | '/prospeccao/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/base-conhecimento'
    | '/configuracoes'
    | '/conteudo'
    | '/crm'
    | '/empresas'
    | '/financeiro'
    | '/growth'
    | '/ia'
    | '/inbox'
    | '/marketing'
    | '/mensagens'
    | '/projetos'
    | '/prospeccao'
    | '/reset-password'
    | '/super-admin'
    | '/suporte'
    | '/tarefas'
    | '/crm/$id'
    | '/empresas/$id'
    | '/growth/cadencias'
    | '/growth/dashboard'
    | '/prospeccao/$id'
    | '/prospeccao/lista'
    | '/super-admin/configuracoes'
    | '/super-admin/logs'
    | '/super-admin/usuarios'
    | '/super-admin/workspaces'
    | '/prospeccao/'
    | '/super-admin/'
    | '/api/webhooks/zapzap'
    | '/crm/$id/contratos'
    | '/crm/$id/propostas'
    | '/crm/$id/timeline'
    | '/empresas/$id/comercial'
    | '/empresas/$id/contatos'
    | '/empresas/$id/financeiro'
    | '/empresas/$id/projetos'
    | '/empresas/$id/suporte'
    | '/empresas/$id/timeline'
    | '/prospeccao/$id/editar'
    | '/prospeccao/$id/historico'
    | '/prospeccao/$id/interacoes'
    | '/prospeccao/$id/proximas-acoes'
    | '/crm/$id/'
    | '/empresas/$id/'
    | '/prospeccao/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BaseConhecimentoRoute: typeof BaseConhecimentoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ConteudoRoute: typeof ConteudoRoute
  CrmRoute: typeof CrmRouteWithChildren
  EmpresasRoute: typeof EmpresasRouteWithChildren
  FinanceiroRoute: typeof FinanceiroRoute
  GrowthRoute: typeof GrowthRouteWithChildren
  IaRoute: typeof IaRoute
  InboxRoute: typeof InboxRoute
  MarketingRoute: typeof MarketingRoute
  MensagensRoute: typeof MensagensRoute
  ProjetosRoute: typeof ProjetosRoute
  ProspeccaoRoute: typeof ProspeccaoRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
  SuporteRoute: typeof SuporteRoute
  TarefasRoute: typeof TarefasRoute
  ApiWebhooksZapzapRoute: typeof ApiWebhooksZapzapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospeccao': {
      id: '/prospeccao'
      path: '/prospeccao'
      fullPath: '/prospeccao'
      preLoaderRoute: typeof ProspeccaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens': {
      id: '/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof MensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth': {
      id: '/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof GrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudo': {
      id: '/conteudo'
      path: '/conteudo'
      fullPath: '/conteudo'
      preLoaderRoute: typeof ConteudoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-conhecimento': {
      id: '/base-conhecimento'
      path: '/base-conhecimento'
      fullPath: '/base-conhecimento'
      preLoaderRoute: typeof BaseConhecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/prospeccao/': {
      id: '/prospeccao/'
      path: '/'
      fullPath: '/prospeccao/'
      preLoaderRoute: typeof ProspeccaoIndexRouteImport
      parentRoute: typeof ProspeccaoRoute
    }
    '/super-admin/workspaces': {
      id: '/super-admin/workspaces'
      path: '/workspaces'
      fullPath: '/super-admin/workspaces'
      preLoaderRoute: typeof SuperAdminWorkspacesRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/usuarios': {
      id: '/super-admin/usuarios'
      path: '/usuarios'
      fullPath: '/super-admin/usuarios'
      preLoaderRoute: typeof SuperAdminUsuariosRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/logs': {
      id: '/super-admin/logs'
      path: '/logs'
      fullPath: '/super-admin/logs'
      preLoaderRoute: typeof SuperAdminLogsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/configuracoes': {
      id: '/super-admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/super-admin/configuracoes'
      preLoaderRoute: typeof SuperAdminConfiguracoesRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/prospeccao/lista': {
      id: '/prospeccao/lista'
      path: '/lista'
      fullPath: '/prospeccao/lista'
      preLoaderRoute: typeof ProspeccaoListaRouteImport
      parentRoute: typeof ProspeccaoRoute
    }
    '/prospeccao/$id': {
      id: '/prospeccao/$id'
      path: '/$id'
      fullPath: '/prospeccao/$id'
      preLoaderRoute: typeof ProspeccaoIdRouteImport
      parentRoute: typeof ProspeccaoRoute
    }
    '/growth/dashboard': {
      id: '/growth/dashboard'
      path: '/dashboard'
      fullPath: '/growth/dashboard'
      preLoaderRoute: typeof GrowthDashboardRouteImport
      parentRoute: typeof GrowthRoute
    }
    '/growth/cadencias': {
      id: '/growth/cadencias'
      path: '/cadencias'
      fullPath: '/growth/cadencias'
      preLoaderRoute: typeof GrowthCadenciasRouteImport
      parentRoute: typeof GrowthRoute
    }
    '/empresas/$id': {
      id: '/empresas/$id'
      path: '/$id'
      fullPath: '/empresas/$id'
      preLoaderRoute: typeof EmpresasIdRouteImport
      parentRoute: typeof EmpresasRoute
    }
    '/crm/$id': {
      id: '/crm/$id'
      path: '/$id'
      fullPath: '/crm/$id'
      preLoaderRoute: typeof CrmIdRouteImport
      parentRoute: typeof CrmRoute
    }
    '/prospeccao/$id/': {
      id: '/prospeccao/$id/'
      path: '/'
      fullPath: '/prospeccao/$id/'
      preLoaderRoute: typeof ProspeccaoIdIndexRouteImport
      parentRoute: typeof ProspeccaoIdRoute
    }
    '/empresas/$id/': {
      id: '/empresas/$id/'
      path: '/'
      fullPath: '/empresas/$id/'
      preLoaderRoute: typeof EmpresasIdIndexRouteImport
      parentRoute: typeof EmpresasIdRoute
    }
    '/crm/$id/': {
      id: '/crm/$id/'
      path: '/'
      fullPath: '/crm/$id/'
      preLoaderRoute: typeof CrmIdIndexRouteImport
      parentRoute: typeof CrmIdRoute
    }
    '/prospeccao/$id/proximas-acoes': {
      id: '/prospeccao/$id/proximas-acoes'
      path: '/proximas-acoes'
      fullPath: '/prospeccao/$id/proximas-acoes'
      preLoaderRoute: typeof ProspeccaoIdProximasAcoesRouteImport
      parentRoute: typeof ProspeccaoIdRoute
    }
    '/prospeccao/$id/interacoes': {
      id: '/prospeccao/$id/interacoes'
      path: '/interacoes'
      fullPath: '/prospeccao/$id/interacoes'
      preLoaderRoute: typeof ProspeccaoIdInteracoesRouteImport
      parentRoute: typeof ProspeccaoIdRoute
    }
    '/prospeccao/$id/historico': {
      id: '/prospeccao/$id/historico'
      path: '/historico'
      fullPath: '/prospeccao/$id/historico'
      preLoaderRoute: typeof ProspeccaoIdHistoricoRouteImport
      parentRoute: typeof ProspeccaoIdRoute
    }
    '/prospeccao/$id/editar': {
      id: '/prospeccao/$id/editar'
      path: '/editar'
      fullPath: '/prospeccao/$id/editar'
      preLoaderRoute: typeof ProspeccaoIdEditarRouteImport
      parentRoute: typeof ProspeccaoIdRoute
    }
    '/empresas/$id/timeline': {
      id: '/empresas/$id/timeline'
      path: '/timeline'
      fullPath: '/empresas/$id/timeline'
      preLoaderRoute: typeof EmpresasIdTimelineRouteImport
      parentRoute: typeof EmpresasIdRoute
    }
    '/empresas/$id/suporte': {
      id: '/empresas/$id/suporte'
      path: '/suporte'
      fullPath: '/empresas/$id/suporte'
      preLoaderRoute: typeof EmpresasIdSuporteRouteImport
      parentRoute: typeof EmpresasIdRoute
    }
    '/empresas/$id/projetos': {
      id: '/empresas/$id/projetos'
      path: '/projetos'
      fullPath: '/empresas/$id/projetos'
      preLoaderRoute: typeof EmpresasIdProjetosRouteImport
      parentRoute: typeof EmpresasIdRoute
    }
    '/empresas/$id/financeiro': {
      id: '/empresas/$id/financeiro'
      path: '/financeiro'
      fullPath: '/empresas/$id/financeiro'
      preLoaderRoute: typeof EmpresasIdFinanceiroRouteImport
      parentRoute: typeof EmpresasIdRoute
    }
    '/empresas/$id/contatos': {
      id: '/empresas/$id/contatos'
      path: '/contatos'
      fullPath: '/empresas/$id/contatos'
      preLoaderRoute: typeof EmpresasIdContatosRouteImport
      parentRoute: typeof EmpresasIdRoute
    }
    '/empresas/$id/comercial': {
      id: '/empresas/$id/comercial'
      path: '/comercial'
      fullPath: '/empresas/$id/comercial'
      preLoaderRoute: typeof EmpresasIdComercialRouteImport
      parentRoute: typeof EmpresasIdRoute
    }
    '/crm/$id/timeline': {
      id: '/crm/$id/timeline'
      path: '/timeline'
      fullPath: '/crm/$id/timeline'
      preLoaderRoute: typeof CrmIdTimelineRouteImport
      parentRoute: typeof CrmIdRoute
    }
    '/crm/$id/propostas': {
      id: '/crm/$id/propostas'
      path: '/propostas'
      fullPath: '/crm/$id/propostas'
      preLoaderRoute: typeof CrmIdPropostasRouteImport
      parentRoute: typeof CrmIdRoute
    }
    '/crm/$id/contratos': {
      id: '/crm/$id/contratos'
      path: '/contratos'
      fullPath: '/crm/$id/contratos'
      preLoaderRoute: typeof CrmIdContratosRouteImport
      parentRoute: typeof CrmIdRoute
    }
    '/api/webhooks/zapzap': {
      id: '/api/webhooks/zapzap'
      path: '/api/webhooks/zapzap'
      fullPath: '/api/webhooks/zapzap'
      preLoaderRoute: typeof ApiWebhooksZapzapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CrmIdRouteChildren {
  CrmIdContratosRoute: typeof CrmIdContratosRoute
  CrmIdPropostasRoute: typeof CrmIdPropostasRoute
  CrmIdTimelineRoute: typeof CrmIdTimelineRoute
  CrmIdIndexRoute: typeof CrmIdIndexRoute
}

const CrmIdRouteChildren: CrmIdRouteChildren = {
  CrmIdContratosRoute: CrmIdContratosRoute,
  CrmIdPropostasRoute: CrmIdPropostasRoute,
  CrmIdTimelineRoute: CrmIdTimelineRoute,
  CrmIdIndexRoute: CrmIdIndexRoute,
}

const CrmIdRouteWithChildren = CrmIdRoute._addFileChildren(CrmIdRouteChildren)

interface CrmRouteChildren {
  CrmIdRoute: typeof CrmIdRouteWithChildren
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmIdRoute: CrmIdRouteWithChildren,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

interface EmpresasIdRouteChildren {
  EmpresasIdComercialRoute: typeof EmpresasIdComercialRoute
  EmpresasIdContatosRoute: typeof EmpresasIdContatosRoute
  EmpresasIdFinanceiroRoute: typeof EmpresasIdFinanceiroRoute
  EmpresasIdProjetosRoute: typeof EmpresasIdProjetosRoute
  EmpresasIdSuporteRoute: typeof EmpresasIdSuporteRoute
  EmpresasIdTimelineRoute: typeof EmpresasIdTimelineRoute
  EmpresasIdIndexRoute: typeof EmpresasIdIndexRoute
}

const EmpresasIdRouteChildren: EmpresasIdRouteChildren = {
  EmpresasIdComercialRoute: EmpresasIdComercialRoute,
  EmpresasIdContatosRoute: EmpresasIdContatosRoute,
  EmpresasIdFinanceiroRoute: EmpresasIdFinanceiroRoute,
  EmpresasIdProjetosRoute: EmpresasIdProjetosRoute,
  EmpresasIdSuporteRoute: EmpresasIdSuporteRoute,
  EmpresasIdTimelineRoute: EmpresasIdTimelineRoute,
  EmpresasIdIndexRoute: EmpresasIdIndexRoute,
}

const EmpresasIdRouteWithChildren = EmpresasIdRoute._addFileChildren(
  EmpresasIdRouteChildren,
)

interface EmpresasRouteChildren {
  EmpresasIdRoute: typeof EmpresasIdRouteWithChildren
}

const EmpresasRouteChildren: EmpresasRouteChildren = {
  EmpresasIdRoute: EmpresasIdRouteWithChildren,
}

const EmpresasRouteWithChildren = EmpresasRoute._addFileChildren(
  EmpresasRouteChildren,
)

interface GrowthRouteChildren {
  GrowthCadenciasRoute: typeof GrowthCadenciasRoute
  GrowthDashboardRoute: typeof GrowthDashboardRoute
}

const GrowthRouteChildren: GrowthRouteChildren = {
  GrowthCadenciasRoute: GrowthCadenciasRoute,
  GrowthDashboardRoute: GrowthDashboardRoute,
}

const GrowthRouteWithChildren =
  GrowthRoute._addFileChildren(GrowthRouteChildren)

interface ProspeccaoIdRouteChildren {
  ProspeccaoIdEditarRoute: typeof ProspeccaoIdEditarRoute
  ProspeccaoIdHistoricoRoute: typeof ProspeccaoIdHistoricoRoute
  ProspeccaoIdInteracoesRoute: typeof ProspeccaoIdInteracoesRoute
  ProspeccaoIdProximasAcoesRoute: typeof ProspeccaoIdProximasAcoesRoute
  ProspeccaoIdIndexRoute: typeof ProspeccaoIdIndexRoute
}

const ProspeccaoIdRouteChildren: ProspeccaoIdRouteChildren = {
  ProspeccaoIdEditarRoute: ProspeccaoIdEditarRoute,
  ProspeccaoIdHistoricoRoute: ProspeccaoIdHistoricoRoute,
  ProspeccaoIdInteracoesRoute: ProspeccaoIdInteracoesRoute,
  ProspeccaoIdProximasAcoesRoute: ProspeccaoIdProximasAcoesRoute,
  ProspeccaoIdIndexRoute: ProspeccaoIdIndexRoute,
}

const ProspeccaoIdRouteWithChildren = ProspeccaoIdRoute._addFileChildren(
  ProspeccaoIdRouteChildren,
)

interface ProspeccaoRouteChildren {
  ProspeccaoIdRoute: typeof ProspeccaoIdRouteWithChildren
  ProspeccaoListaRoute: typeof ProspeccaoListaRoute
  ProspeccaoIndexRoute: typeof ProspeccaoIndexRoute
}

const ProspeccaoRouteChildren: ProspeccaoRouteChildren = {
  ProspeccaoIdRoute: ProspeccaoIdRouteWithChildren,
  ProspeccaoListaRoute: ProspeccaoListaRoute,
  ProspeccaoIndexRoute: ProspeccaoIndexRoute,
}

const ProspeccaoRouteWithChildren = ProspeccaoRoute._addFileChildren(
  ProspeccaoRouteChildren,
)

interface SuperAdminRouteChildren {
  SuperAdminConfiguracoesRoute: typeof SuperAdminConfiguracoesRoute
  SuperAdminLogsRoute: typeof SuperAdminLogsRoute
  SuperAdminUsuariosRoute: typeof SuperAdminUsuariosRoute
  SuperAdminWorkspacesRoute: typeof SuperAdminWorkspacesRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminConfiguracoesRoute: SuperAdminConfiguracoesRoute,
  SuperAdminLogsRoute: SuperAdminLogsRoute,
  SuperAdminUsuariosRoute: SuperAdminUsuariosRoute,
  SuperAdminWorkspacesRoute: SuperAdminWorkspacesRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BaseConhecimentoRoute: BaseConhecimentoRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ConteudoRoute: ConteudoRoute,
  CrmRoute: CrmRouteWithChildren,
  EmpresasRoute: EmpresasRouteWithChildren,
  FinanceiroRoute: FinanceiroRoute,
  GrowthRoute: GrowthRouteWithChildren,
  IaRoute: IaRoute,
  InboxRoute: InboxRoute,
  MarketingRoute: MarketingRoute,
  MensagensRoute: MensagensRoute,
  ProjetosRoute: ProjetosRoute,
  ProspeccaoRoute: ProspeccaoRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  SuporteRoute: SuporteRoute,
  TarefasRoute: TarefasRoute,
  ApiWebhooksZapzapRoute: ApiWebhooksZapzapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
