/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as ProspeccaoRouteImport } from './routes/prospeccao'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as IaRouteImport } from './routes/ia'
import { Route as GrowthRouteImport } from './routes/growth'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ConteudoRouteImport } from './routes/conteudo'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as BaseConhecimentoRouteImport } from './routes/base-conhecimento'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProspeccaoIdRouteImport } from './routes/prospeccao.$id'
import { Route as EmpresasIdRouteImport } from './routes/empresas.$id'
import { Route as CrmIdRouteImport } from './routes/crm.$id'
import { Route as ProspeccaoIdIndexRouteImport } from './routes/prospeccao.$id.index'
import { Route as EmpresasIdIndexRouteImport } from './routes/empresas.$id.index'
import { Route as CrmIdIndexRouteImport } from './routes/crm.$id.index'
import { Route as ProspeccaoIdProximasAcoesRouteImport } from './routes/prospeccao.$id.proximas-acoes'
import { Route as ProspeccaoIdInteracoesRouteImport } from './routes/prospeccao.$id.interacoes'
import { Route as ProspeccaoIdHistoricoRouteImport } from './routes/prospeccao.$id.historico'
import { Route as EmpresasIdTimelineRouteImport } from './routes/empresas.$id.timeline'
import { Route as EmpresasIdSuporteRouteImport } from './routes/empresas.$id.suporte'
import { Route as EmpresasIdProjetosRouteImport } from './routes/empresas.$id.projetos'
import { Route as EmpresasIdFinanceiroRouteImport } from './routes/empresas.$id.financeiro'
import { Route as EmpresasIdContatosRouteImport } from './routes/empresas.$id.contatos'
import { Route as EmpresasIdComercialRouteImport } from './routes/empresas.$id.comercial'
import { Route as CrmIdTimelineRouteImport } from './routes/crm.$id.timeline'
import { Route as CrmIdPropostasRouteImport } from './routes/crm.$id.propostas'

const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspeccaoRoute = ProspeccaoRouteImport.update({
  id: '/prospeccao',
  path: '/prospeccao',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthRoute = GrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudoRoute = ConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseConhecimentoRoute = BaseConhecimentoRouteImport.update({
  id: '/base-conhecimento',
  path: '/base-conhecimento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspeccaoIdRoute = ProspeccaoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProspeccaoRoute,
} as any)
const EmpresasIdRoute = EmpresasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EmpresasRoute,
} as any)
const CrmIdRoute = CrmIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CrmRoute,
} as any)
const ProspeccaoIdIndexRoute = ProspeccaoIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProspeccaoIdRoute,
} as any)
const EmpresasIdIndexRoute = EmpresasIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmpresasIdRoute,
} as any)
const CrmIdIndexRoute = CrmIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmIdRoute,
} as any)
const ProspeccaoIdProximasAcoesRoute =
  ProspeccaoIdProximasAcoesRouteImport.update({
    id: '/proximas-acoes',
    path: '/proximas-acoes',
    getParentRoute: () => ProspeccaoIdRoute,
  } as any)
const ProspeccaoIdInteracoesRoute = ProspeccaoIdInteracoesRouteImport.update({
  id: '/interacoes',
  path: '/interacoes',
  getParentRoute: () => ProspeccaoIdRoute,
} as any)
const ProspeccaoIdHistoricoRoute = ProspeccaoIdHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => ProspeccaoIdRoute,
} as any)
const EmpresasIdTimelineRoute = EmpresasIdTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => EmpresasIdRoute,
} as any)
const EmpresasIdSuporteRoute = EmpresasIdSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => EmpresasIdRoute,
} as any)
const EmpresasIdProjetosRoute = EmpresasIdProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => EmpresasIdRoute,
} as any)
const EmpresasIdFinanceiroRoute = EmpresasIdFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => EmpresasIdRoute,
} as any)
const EmpresasIdContatosRoute = EmpresasIdContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => EmpresasIdRoute,
} as any)
const EmpresasIdComercialRoute = EmpresasIdComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => EmpresasIdRoute,
} as any)
const CrmIdTimelineRoute = CrmIdTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => CrmIdRoute,
} as any)
const CrmIdPropostasRoute = CrmIdPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => CrmIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/base-conhecimento': typeof BaseConhecimentoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conteudo': typeof ConteudoRoute
  '/crm': typeof CrmRouteWithChildren
  '/empresas': typeof EmpresasRouteWithChildren
  '/financeiro': typeof FinanceiroRoute
  '/growth': typeof GrowthRoute
  '/ia': typeof IaRoute
  '/marketing': typeof MarketingRoute
  '/projetos': typeof ProjetosRoute
  '/prospeccao': typeof ProspeccaoRouteWithChildren
  '/suporte': typeof SuporteRoute
  '/crm/$id': typeof CrmIdRouteWithChildren
  '/empresas/$id': typeof EmpresasIdRouteWithChildren
  '/prospeccao/$id': typeof ProspeccaoIdRouteWithChildren
  '/crm/$id/propostas': typeof CrmIdPropostasRoute
  '/crm/$id/timeline': typeof CrmIdTimelineRoute
  '/empresas/$id/comercial': typeof EmpresasIdComercialRoute
  '/empresas/$id/contatos': typeof EmpresasIdContatosRoute
  '/empresas/$id/financeiro': typeof EmpresasIdFinanceiroRoute
  '/empresas/$id/projetos': typeof EmpresasIdProjetosRoute
  '/empresas/$id/suporte': typeof EmpresasIdSuporteRoute
  '/empresas/$id/timeline': typeof EmpresasIdTimelineRoute
  '/prospeccao/$id/historico': typeof ProspeccaoIdHistoricoRoute
  '/prospeccao/$id/interacoes': typeof ProspeccaoIdInteracoesRoute
  '/prospeccao/$id/proximas-acoes': typeof ProspeccaoIdProximasAcoesRoute
  '/crm/$id/': typeof CrmIdIndexRoute
  '/empresas/$id/': typeof EmpresasIdIndexRoute
  '/prospeccao/$id/': typeof ProspeccaoIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/base-conhecimento': typeof BaseConhecimentoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conteudo': typeof ConteudoRoute
  '/crm': typeof CrmRouteWithChildren
  '/empresas': typeof EmpresasRouteWithChildren
  '/financeiro': typeof FinanceiroRoute
  '/growth': typeof GrowthRoute
  '/ia': typeof IaRoute
  '/marketing': typeof MarketingRoute
  '/projetos': typeof ProjetosRoute
  '/prospeccao': typeof ProspeccaoRouteWithChildren
  '/suporte': typeof SuporteRoute
  '/crm/$id/propostas': typeof CrmIdPropostasRoute
  '/crm/$id/timeline': typeof CrmIdTimelineRoute
  '/empresas/$id/comercial': typeof EmpresasIdComercialRoute
  '/empresas/$id/contatos': typeof EmpresasIdContatosRoute
  '/empresas/$id/financeiro': typeof EmpresasIdFinanceiroRoute
  '/empresas/$id/projetos': typeof EmpresasIdProjetosRoute
  '/empresas/$id/suporte': typeof EmpresasIdSuporteRoute
  '/empresas/$id/timeline': typeof EmpresasIdTimelineRoute
  '/prospeccao/$id/historico': typeof ProspeccaoIdHistoricoRoute
  '/prospeccao/$id/interacoes': typeof ProspeccaoIdInteracoesRoute
  '/prospeccao/$id/proximas-acoes': typeof ProspeccaoIdProximasAcoesRoute
  '/crm/$id': typeof CrmIdIndexRoute
  '/empresas/$id': typeof EmpresasIdIndexRoute
  '/prospeccao/$id': typeof ProspeccaoIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/base-conhecimento': typeof BaseConhecimentoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conteudo': typeof ConteudoRoute
  '/crm': typeof CrmRouteWithChildren
  '/empresas': typeof EmpresasRouteWithChildren
  '/financeiro': typeof FinanceiroRoute
  '/growth': typeof GrowthRoute
  '/ia': typeof IaRoute
  '/marketing': typeof MarketingRoute
  '/projetos': typeof ProjetosRoute
  '/prospeccao': typeof ProspeccaoRouteWithChildren
  '/suporte': typeof SuporteRoute
  '/crm/$id': typeof CrmIdRouteWithChildren
  '/empresas/$id': typeof EmpresasIdRouteWithChildren
  '/prospeccao/$id': typeof ProspeccaoIdRouteWithChildren
  '/crm/$id/propostas': typeof CrmIdPropostasRoute
  '/crm/$id/timeline': typeof CrmIdTimelineRoute
  '/empresas/$id/comercial': typeof EmpresasIdComercialRoute
  '/empresas/$id/contatos': typeof EmpresasIdContatosRoute
  '/empresas/$id/financeiro': typeof EmpresasIdFinanceiroRoute
  '/empresas/$id/projetos': typeof EmpresasIdProjetosRoute
  '/empresas/$id/suporte': typeof EmpresasIdSuporteRoute
  '/empresas/$id/timeline': typeof EmpresasIdTimelineRoute
  '/prospeccao/$id/historico': typeof ProspeccaoIdHistoricoRoute
  '/prospeccao/$id/interacoes': typeof ProspeccaoIdInteracoesRoute
  '/prospeccao/$id/proximas-acoes': typeof ProspeccaoIdProximasAcoesRoute
  '/crm/$id/': typeof CrmIdIndexRoute
  '/empresas/$id/': typeof EmpresasIdIndexRoute
  '/prospeccao/$id/': typeof ProspeccaoIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/base-conhecimento'
    | '/configuracoes'
    | '/conteudo'
    | '/crm'
    | '/empresas'
    | '/financeiro'
    | '/growth'
    | '/ia'
    | '/marketing'
    | '/projetos'
    | '/prospeccao'
    | '/suporte'
    | '/crm/$id'
    | '/empresas/$id'
    | '/prospeccao/$id'
    | '/crm/$id/propostas'
    | '/crm/$id/timeline'
    | '/empresas/$id/comercial'
    | '/empresas/$id/contatos'
    | '/empresas/$id/financeiro'
    | '/empresas/$id/projetos'
    | '/empresas/$id/suporte'
    | '/empresas/$id/timeline'
    | '/prospeccao/$id/historico'
    | '/prospeccao/$id/interacoes'
    | '/prospeccao/$id/proximas-acoes'
    | '/crm/$id/'
    | '/empresas/$id/'
    | '/prospeccao/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/base-conhecimento'
    | '/configuracoes'
    | '/conteudo'
    | '/crm'
    | '/empresas'
    | '/financeiro'
    | '/growth'
    | '/ia'
    | '/marketing'
    | '/projetos'
    | '/prospeccao'
    | '/suporte'
    | '/crm/$id/propostas'
    | '/crm/$id/timeline'
    | '/empresas/$id/comercial'
    | '/empresas/$id/contatos'
    | '/empresas/$id/financeiro'
    | '/empresas/$id/projetos'
    | '/empresas/$id/suporte'
    | '/empresas/$id/timeline'
    | '/prospeccao/$id/historico'
    | '/prospeccao/$id/interacoes'
    | '/prospeccao/$id/proximas-acoes'
    | '/crm/$id'
    | '/empresas/$id'
    | '/prospeccao/$id'
  id:
    | '__root__'
    | '/'
    | '/base-conhecimento'
    | '/configuracoes'
    | '/conteudo'
    | '/crm'
    | '/empresas'
    | '/financeiro'
    | '/growth'
    | '/ia'
    | '/marketing'
    | '/projetos'
    | '/prospeccao'
    | '/suporte'
    | '/crm/$id'
    | '/empresas/$id'
    | '/prospeccao/$id'
    | '/crm/$id/propostas'
    | '/crm/$id/timeline'
    | '/empresas/$id/comercial'
    | '/empresas/$id/contatos'
    | '/empresas/$id/financeiro'
    | '/empresas/$id/projetos'
    | '/empresas/$id/suporte'
    | '/empresas/$id/timeline'
    | '/prospeccao/$id/historico'
    | '/prospeccao/$id/interacoes'
    | '/prospeccao/$id/proximas-acoes'
    | '/crm/$id/'
    | '/empresas/$id/'
    | '/prospeccao/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaseConhecimentoRoute: typeof BaseConhecimentoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ConteudoRoute: typeof ConteudoRoute
  CrmRoute: typeof CrmRouteWithChildren
  EmpresasRoute: typeof EmpresasRouteWithChildren
  FinanceiroRoute: typeof FinanceiroRoute
  GrowthRoute: typeof GrowthRoute
  IaRoute: typeof IaRoute
  MarketingRoute: typeof MarketingRoute
  ProjetosRoute: typeof ProjetosRoute
  ProspeccaoRoute: typeof ProspeccaoRouteWithChildren
  SuporteRoute: typeof SuporteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospeccao': {
      id: '/prospeccao'
      path: '/prospeccao'
      fullPath: '/prospeccao'
      preLoaderRoute: typeof ProspeccaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth': {
      id: '/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof GrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudo': {
      id: '/conteudo'
      path: '/conteudo'
      fullPath: '/conteudo'
      preLoaderRoute: typeof ConteudoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-conhecimento': {
      id: '/base-conhecimento'
      path: '/base-conhecimento'
      fullPath: '/base-conhecimento'
      preLoaderRoute: typeof BaseConhecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospeccao/$id': {
      id: '/prospeccao/$id'
      path: '/$id'
      fullPath: '/prospeccao/$id'
      preLoaderRoute: typeof ProspeccaoIdRouteImport
      parentRoute: typeof ProspeccaoRoute
    }
    '/empresas/$id': {
      id: '/empresas/$id'
      path: '/$id'
      fullPath: '/empresas/$id'
      preLoaderRoute: typeof EmpresasIdRouteImport
      parentRoute: typeof EmpresasRoute
    }
    '/crm/$id': {
      id: '/crm/$id'
      path: '/$id'
      fullPath: '/crm/$id'
      preLoaderRoute: typeof CrmIdRouteImport
      parentRoute: typeof CrmRoute
    }
    '/prospeccao/$id/': {
      id: '/prospeccao/$id/'
      path: '/'
      fullPath: '/prospeccao/$id/'
      preLoaderRoute: typeof ProspeccaoIdIndexRouteImport
      parentRoute: typeof ProspeccaoIdRoute
    }
    '/empresas/$id/': {
      id: '/empresas/$id/'
      path: '/'
      fullPath: '/empresas/$id/'
      preLoaderRoute: typeof EmpresasIdIndexRouteImport
      parentRoute: typeof EmpresasIdRoute
    }
    '/crm/$id/': {
      id: '/crm/$id/'
      path: '/'
      fullPath: '/crm/$id/'
      preLoaderRoute: typeof CrmIdIndexRouteImport
      parentRoute: typeof CrmIdRoute
    }
    '/prospeccao/$id/proximas-acoes': {
      id: '/prospeccao/$id/proximas-acoes'
      path: '/proximas-acoes'
      fullPath: '/prospeccao/$id/proximas-acoes'
      preLoaderRoute: typeof ProspeccaoIdProximasAcoesRouteImport
      parentRoute: typeof ProspeccaoIdRoute
    }
    '/prospeccao/$id/interacoes': {
      id: '/prospeccao/$id/interacoes'
      path: '/interacoes'
      fullPath: '/prospeccao/$id/interacoes'
      preLoaderRoute: typeof ProspeccaoIdInteracoesRouteImport
      parentRoute: typeof ProspeccaoIdRoute
    }
    '/prospeccao/$id/historico': {
      id: '/prospeccao/$id/historico'
      path: '/historico'
      fullPath: '/prospeccao/$id/historico'
      preLoaderRoute: typeof ProspeccaoIdHistoricoRouteImport
      parentRoute: typeof ProspeccaoIdRoute
    }
    '/empresas/$id/timeline': {
      id: '/empresas/$id/timeline'
      path: '/timeline'
      fullPath: '/empresas/$id/timeline'
      preLoaderRoute: typeof EmpresasIdTimelineRouteImport
      parentRoute: typeof EmpresasIdRoute
    }
    '/empresas/$id/suporte': {
      id: '/empresas/$id/suporte'
      path: '/suporte'
      fullPath: '/empresas/$id/suporte'
      preLoaderRoute: typeof EmpresasIdSuporteRouteImport
      parentRoute: typeof EmpresasIdRoute
    }
    '/empresas/$id/projetos': {
      id: '/empresas/$id/projetos'
      path: '/projetos'
      fullPath: '/empresas/$id/projetos'
      preLoaderRoute: typeof EmpresasIdProjetosRouteImport
      parentRoute: typeof EmpresasIdRoute
    }
    '/empresas/$id/financeiro': {
      id: '/empresas/$id/financeiro'
      path: '/financeiro'
      fullPath: '/empresas/$id/financeiro'
      preLoaderRoute: typeof EmpresasIdFinanceiroRouteImport
      parentRoute: typeof EmpresasIdRoute
    }
    '/empresas/$id/contatos': {
      id: '/empresas/$id/contatos'
      path: '/contatos'
      fullPath: '/empresas/$id/contatos'
      preLoaderRoute: typeof EmpresasIdContatosRouteImport
      parentRoute: typeof EmpresasIdRoute
    }
    '/empresas/$id/comercial': {
      id: '/empresas/$id/comercial'
      path: '/comercial'
      fullPath: '/empresas/$id/comercial'
      preLoaderRoute: typeof EmpresasIdComercialRouteImport
      parentRoute: typeof EmpresasIdRoute
    }
    '/crm/$id/timeline': {
      id: '/crm/$id/timeline'
      path: '/timeline'
      fullPath: '/crm/$id/timeline'
      preLoaderRoute: typeof CrmIdTimelineRouteImport
      parentRoute: typeof CrmIdRoute
    }
    '/crm/$id/propostas': {
      id: '/crm/$id/propostas'
      path: '/propostas'
      fullPath: '/crm/$id/propostas'
      preLoaderRoute: typeof CrmIdPropostasRouteImport
      parentRoute: typeof CrmIdRoute
    }
  }
}

interface CrmIdRouteChildren {
  CrmIdPropostasRoute: typeof CrmIdPropostasRoute
  CrmIdTimelineRoute: typeof CrmIdTimelineRoute
  CrmIdIndexRoute: typeof CrmIdIndexRoute
}

const CrmIdRouteChildren: CrmIdRouteChildren = {
  CrmIdPropostasRoute: CrmIdPropostasRoute,
  CrmIdTimelineRoute: CrmIdTimelineRoute,
  CrmIdIndexRoute: CrmIdIndexRoute,
}

const CrmIdRouteWithChildren = CrmIdRoute._addFileChildren(CrmIdRouteChildren)

interface CrmRouteChildren {
  CrmIdRoute: typeof CrmIdRouteWithChildren
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmIdRoute: CrmIdRouteWithChildren,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

interface EmpresasIdRouteChildren {
  EmpresasIdComercialRoute: typeof EmpresasIdComercialRoute
  EmpresasIdContatosRoute: typeof EmpresasIdContatosRoute
  EmpresasIdFinanceiroRoute: typeof EmpresasIdFinanceiroRoute
  EmpresasIdProjetosRoute: typeof EmpresasIdProjetosRoute
  EmpresasIdSuporteRoute: typeof EmpresasIdSuporteRoute
  EmpresasIdTimelineRoute: typeof EmpresasIdTimelineRoute
  EmpresasIdIndexRoute: typeof EmpresasIdIndexRoute
}

const EmpresasIdRouteChildren: EmpresasIdRouteChildren = {
  EmpresasIdComercialRoute: EmpresasIdComercialRoute,
  EmpresasIdContatosRoute: EmpresasIdContatosRoute,
  EmpresasIdFinanceiroRoute: EmpresasIdFinanceiroRoute,
  EmpresasIdProjetosRoute: EmpresasIdProjetosRoute,
  EmpresasIdSuporteRoute: EmpresasIdSuporteRoute,
  EmpresasIdTimelineRoute: EmpresasIdTimelineRoute,
  EmpresasIdIndexRoute: EmpresasIdIndexRoute,
}

const EmpresasIdRouteWithChildren = EmpresasIdRoute._addFileChildren(
  EmpresasIdRouteChildren,
)

interface EmpresasRouteChildren {
  EmpresasIdRoute: typeof EmpresasIdRouteWithChildren
}

const EmpresasRouteChildren: EmpresasRouteChildren = {
  EmpresasIdRoute: EmpresasIdRouteWithChildren,
}

const EmpresasRouteWithChildren = EmpresasRoute._addFileChildren(
  EmpresasRouteChildren,
)

interface ProspeccaoIdRouteChildren {
  ProspeccaoIdHistoricoRoute: typeof ProspeccaoIdHistoricoRoute
  ProspeccaoIdInteracoesRoute: typeof ProspeccaoIdInteracoesRoute
  ProspeccaoIdProximasAcoesRoute: typeof ProspeccaoIdProximasAcoesRoute
  ProspeccaoIdIndexRoute: typeof ProspeccaoIdIndexRoute
}

const ProspeccaoIdRouteChildren: ProspeccaoIdRouteChildren = {
  ProspeccaoIdHistoricoRoute: ProspeccaoIdHistoricoRoute,
  ProspeccaoIdInteracoesRoute: ProspeccaoIdInteracoesRoute,
  ProspeccaoIdProximasAcoesRoute: ProspeccaoIdProximasAcoesRoute,
  ProspeccaoIdIndexRoute: ProspeccaoIdIndexRoute,
}

const ProspeccaoIdRouteWithChildren = ProspeccaoIdRoute._addFileChildren(
  ProspeccaoIdRouteChildren,
)

interface ProspeccaoRouteChildren {
  ProspeccaoIdRoute: typeof ProspeccaoIdRouteWithChildren
}

const ProspeccaoRouteChildren: ProspeccaoRouteChildren = {
  ProspeccaoIdRoute: ProspeccaoIdRouteWithChildren,
}

const ProspeccaoRouteWithChildren = ProspeccaoRoute._addFileChildren(
  ProspeccaoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaseConhecimentoRoute: BaseConhecimentoRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ConteudoRoute: ConteudoRoute,
  CrmRoute: CrmRouteWithChildren,
  EmpresasRoute: EmpresasRouteWithChildren,
  FinanceiroRoute: FinanceiroRoute,
  GrowthRoute: GrowthRoute,
  IaRoute: IaRoute,
  MarketingRoute: MarketingRoute,
  ProjetosRoute: ProjetosRoute,
  ProspeccaoRoute: ProspeccaoRouteWithChildren,
  SuporteRoute: SuporteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
